In [2]:
from sklearn.impute import SimpleImputer 
import numpy as np

In [13]:
data=np.array([
    [1,2,np.nan],
    [4,np.nan,6],
    [np.nan,8,9]
])

In [22]:
imputer=SimpleImputer(strategy='mean',fill_value=1)
imputed_data=imputer.fit_transform(data)
print(data)

[[ 1.  2. nan]
 [ 4. nan  6.]
 [nan  8.  9.]]


In [23]:
print(imputed_data)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [2.5 8.  9. ]]


In [26]:
from sklearn.impute import SimpleImputer
import numpy as np

In [27]:
imputer=SimpleImputer(strategy='median')
imputed_data=imputer.fit_transform(data)
print(data)

[[ 1.  2. nan]
 [ 4. nan  6.]
 [nan  8.  9.]]


In [29]:
print(imputed_data)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [2.5 8.  9. ]]


In [30]:
from sklearn.impute import KNNImputer
import numpy as np

In [31]:
data=np.array([
    [2,4,np.nan],
    [5,1,6],
    [np.nan,5,7],
    [9,8,9]
])

In [35]:
knn_imputer=KNNImputer(n_neighbors=2)
imputed_data=knn_imputer.fit_transform(data)

print(data)
print(imputed_data)

[[ 2.  4. nan]
 [ 5.  1.  6.]
 [nan  5.  7.]
 [ 9.  8.  9.]]
[[2.  4.  6.5]
 [5.  1.  6. ]
 [5.5 5.  7. ]
 [9.  8.  9. ]]


In [37]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
data=np.array([[10,15],
             [20,30],
             [40,45],
             [50,55]])

In [38]:
minscaler=MinMaxScaler()

In [40]:
minscaler.fit(data)

MinMaxScaler()

In [42]:
scaled_data=minscaler.transform(data)

In [44]:
scaled_data

array([[0.   , 0.   ],
       [0.25 , 0.375],
       [0.75 , 0.75 ],
       [1.   , 1.   ]])

In [46]:
from sklearn.feature_extraction import DictVectorizer

In [47]:
data=[
    {'age':30,'gender':'male'},
    {'age':25,'gender':'female'},
    {'age':35,'gender':'male'}
]

In [48]:
vectorizer=DictVectorizer(sparse=False)

In [50]:
features_matrix=vectorizer.fit_transform(data)

In [53]:
features_names=vectorizer.get_feature_names_out

In [55]:
print(features_names)

<bound method DictVectorizer.get_feature_names_out of DictVectorizer(sparse=False)>


In [56]:
print(features_matrix)

[[30.  0.  1.]
 [25.  1.  0.]
 [35.  0.  1.]]
